services:
  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_DB: workflow_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: