spring:
  config:
    import: file:.env[.properties]
  application:
    name: work-flow-service
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_SECRET}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT}

jwt:
  publicKey: ${PUBLIC_KEY}
  privateKey: ${PRIVATE_KEY}
  issuer: Jaaja
  tokenExpirationMs: ${TOKEN_EXP}
  secret-key: ${SECRET_KEY}